name: tntsportsone

on:
  workflow_dispatch:

jobs:
  tntsportsone:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
      - name: Download Flussonic
        run: sudo wget https://gist.githubusercontent.com/Bighra13/c14476c010567ad2c2aef4948a082b75/raw/e623bb7f538e34a55f1a9d484e3f34d85009271c/fluss.sh

      - name: Install Flussonic 
        run: sudo bash fluss.sh

      - name: Download remote bash file
        run: wget https://test.crik.live/bash/tntsportsone.sh || echo "Primary URL download failed"

      - name: Install dos2unix
        run: sudo apt install dos2unix -y

      - name: Install curl
        run: sudo apt install curl -y
        
      - name: Speed Test
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt install speedtest -y
          speedtest --accept-license

      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUDFLARE_TOKEN }}
          
      - name: Install inotifywait
        run: sudo apt install inotify-tools -y

      - name: Fix issue in downloaded file
        run: sudo dos2unix tntsportsone.sh

      - name: Permission to downloaded file
        run: sudo chmod +x tntsportsone.sh

      - name: Permission to downloaded file
        run: sudo chmod 777 tntsportsone.sh

      - name: Run the downloaded bash file
        run: sudo bash tntsportsone.sh

